name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_KEY: ${{secrets.MONGODB_KEY  || 'mongodb://dependabot'}}
      AUTH_SECRET: ${{secrets.AUTH_SECRET  || 'dependabot'}}
      AUTH_GITHUB_ID: ${{secrets.AUTH_GITHUB_ID  || 'dependabot'}}
      AUTH_GITHUB_SECRET: ${{secrets.AUTH_GITHUB_SECRET  || 'dependabot'}}
      AUTH_GOOGLE_ID: ${{secrets.AUTH_GOOGLE_ID  || 'dependabot'}}
      AUTH_GOOGLE_SECRET: ${{secrets.AUTH_GOOGLE_SECRET  || 'dependabot'}}
      FREE_PLAN_ID: ${{secrets.FREE_PLAN_ID  || 'dependabot'}}
      BASIC_PLAN_ID: ${{secrets.BASIC_PLAN_ID  || 'dependabot'}}
      PLUS_PLAN_ID: ${{secrets.PLUS_PLAN_ID  || 'dependabot'}}
      PRO_PLAN_ID: ${{secrets.PRO_PLAN_ID  || 'dependabot'}}
      WEBMAIL_USER: ${{secrets. WEBMAIL_USER  || 'dependabot'}}
      WEBMAIL_PASS: ${{secrets.WEBMAIL_PASS  || 'dependabot'}}
      PINATA_JWT: ${{secrets.PINATA_JWT  || 'dependabot'}}
      PINATA_GATEWAY: ${{secrets.PINATA_GATEWAY  || 'dependabot'}}
      LEVEL_ONE_UPGRADE_ID: ${{secrets.LEVEL_ONE_UPGRADE_ID || 'dependabot'}},
      LEVEL_TWO_UPGRADE_ID: ${{secrets.LEVEL_TWO_UPGRADE_ID || 'dependabot'}},
      EMAIL_TOKEN_SUFFIX: ${{secrets.EMAIL_TOKEN_SUFFIX || 'dependabot'}},
      RESEND_API_KEY: ${{secrets.RESEND_API_KEY || 'dependabot'}},
      QSTASH_CURRENT_SIGNING_KEY: ${{secrets.QSTASH_CURRENT_SIGNING_KEY||'dependabot'}},
      QSTASH_NEXT_SIGNING_KEY: ${{secrets.QSTASH_NEXT_SIGNING_KEY||'dependabot'}},
      INTERNAL_API_SECRET: ${{secrets.INTERNAL_API_SECRET || 'dependabot'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint

      - name: Run build
        run: bun run build
